### ISSUE TITLE
On h2vx.com, VCF conversion fails with PHP fatal error

### ISSUE THREAD

**Issue by fabacab** [microformats/h2vx.com#2]
Not entirely sure if this is the right place to report this issue (and apologies if not), but all VCF conversion attempts on h2vx.com now fail with this error:

> Fatal error: Call-time pass-by-reference has been removed in /home/tantek/domains/h2vx.com/public_html/vcf/get-contact.php on line 106

This repo doesn't show its current `get-contact.php` to have this problem on line 106, though, so I wonder if perhaps h2vx.com is running an older version of the software?

**Comment by tantek** [comment]
Can you try dev.h2vx.com with your VCF conversion use-case and let me know if you still see that error?

**Comment by tantek** [comment]
Narrowed it down to an unnecessary & with the help of @aaronpk. Should be fixed for both VCF and ICS conversions now. Could you try it out and see if it's fixed for you?

**Comment by fabacab** [comment]
Yup, working again. Thank you for taking the time to fix this.
